### ISSUE TITLE
Some problems on Mate

### ISSUE THREAD

**Issue by scorninpc** [onli/simdock#10]
Hey, nice work. I loved the simplicity of the dock. So here is some problems i see on Mate 1.20.4 / Debian 10

- Cannot get transparency of PNG

![image](https://user-images.githubusercontent.com/2607849/90137535-24085400-dd4c-11ea-83e9-24be884e5c27.png)

- The dock is not always on the top

![image](https://user-images.githubusercontent.com/2607849/90137453-06d38580-dd4c-11ea-85da-6887fce8108e.png)

- Can move dock using ALT+CLICK

![image](https://user-images.githubusercontent.com/2607849/90137580-35516080-dd4c-11ea-89a8-699ad7f3591f.png)

- A Clock will be nice feature

Anyway, I'll look and try do something, i loved the dock

**Comment by onli** [comment]
Hey, thanks for the report. Just to make sure, did you compile the current version from fit or are you using the appimage?

**Comment by scorninpc** [comment]
Hi

I have compiled, because the old version off appimage does nothing

![image](https://user-images.githubusercontent.com/2607849/90157102-aea87d80-dd63-11ea-88da-d231d4574f7a.png)

The new version released today run, bet same problems as compiled

![image](https://user-images.githubusercontent.com/2607849/90157172-c6800180-dd63-11ea-8ab7-87b0dcc10b0b.png)

**Comment by scorninpc** [comment]
I need ask sorry, because I see on code the --on-top param and now this is working. Maybe can be added on README

But transparency and move with ALT key still present. I'll try to reproduce a minimal code with your method to see if persist

**Comment by onli** [comment]
The thing with the ALT Key is unlikely to change, I'm not aware of an option to block it. But I might miss something!

You are right, the `--on-top` should be added in the README, together with the other options. I haven't look at them in years, or maybe even never.

Transparency, I explained a bit of the background in https://github.com/onli/simdock/issues/6. It is possible Mate has the same issue of not having a real X background. You can try setting one and hope it persist. But what definitely will not work is to see the terminal window - at least on my system wxWidgets compositing support was completely broken.

**Comment by onli** [comment]
The transparency issue might now be fixed, with the recent changes for GTK3.
